core/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Payment IPN

Route::get('/ipnbtc', 'PaymentController@ipnBchain')->name('ipn.bchain');
Route::get('/ipnblockbtc', 'PaymentController@blockIpnBtc')->name('ipn.block.btc');
Route::get('/ipnblocklite', 'PaymentController@blockIpnLite')->name('ipn.block.lite');
Route::get('/ipnblockdog', 'PaymentController@blockIpnDog')->name('ipn.block.dog');
Route::post('/ipnpaypal', 'PaymentController@ipnpaypal')->name('ipn.paypal');
Route::post('/ipnperfect', 'PaymentController@ipnperfect')->name('ipn.perfect');
Route::post('/ipnstripe', 'PaymentController@ipnstripe')->name('ipn.stripe');
Route::post('/ipnskrill', 'PaymentController@skrillIPN')->name('ipn.skrill');
Route::post('/ipncoinpaybtc', 'PaymentController@ipnCoinPayBtc')->name('ipn.coinPay.btc');
Route::post('/ipncoinpayeth', 'PaymentController@ipnCoinPayEth')->name('ipn.coinPay.eth');
Route::post('/ipncoinpaybch', 'PaymentController@ipnCoinPayBch')->name('ipn.coinPay.bch');
Route::post('/ipncoinpaydash', 'PaymentController@ipnCoinPayDash')->name('ipn.coinPay.dash');
Route::post('/ipncoinpaydoge', 'PaymentController@ipnCoinPayDoge')->name('ipn.coinPay.doge');
Route::post('/ipncoinpayltc', 'PaymentController@ipnCoinPayLtc')->name('ipn.coinPay.ltc');
Route::post('/ipncoin', 'PaymentController@ipnCoin')->name('ipn.coinpay');
Route::post('/ipncoingate', 'PaymentController@ipnCoinGate')->name('ipn.coingate');


Route::post('/ipnpaytm', 'PaymentController@ipnPayTm')->name('ipn.paytm');
Route::post('/ipnpayeer', 'PaymentController@ipnPayEer')->name('ipn.payeer');
Route::post('/ipnpaystack', 'PaymentController@ipnPayStack')->name('ipn.paystack');
Route::post('/ipnvoguepay', 'PaymentController@ipnVoguePay')->name('ipn.voguepay');
//Payment IPN


Route::get('/', 'FrontendController@index')->name('homepage');
Route::get('/menu/{slug}', 'FrontendController@menu')->name('menu');
Route::get('/blog', 'FrontendController@blog')->name('blog');
Route::get('/details/{id}/{slug}', 'FrontendController@details')->name('blog.details');
Route::get('/cats/{id}/{slug}', 'FrontendController@categoryByBlog')->name('cats.blog');
Route::get('/about-us', 'FrontendController@about')->name('about');
Route::get('/faqs', 'FrontendController@faqs')->name('faqs');
Route::get('/click-add/{id}', 'FrontendController@clickadd');
Route::get('/contact-us', 'FrontendController@contactUs')->name('contact');
Route::post('/contact-us', 'FrontendController@contactSubmit')->name('contact.submit');
Route::post('/subscribe', 'FrontendController@subscribe')->name('subscribe');


Auth::routes();

Route::get('{provider}/auth', [

'uses'=>'AdminLoginController@facebook_auth',
'as'=>'social.auth'


]);

Route::get('{provider}/redirect', [

'uses'=>'AdminLoginController@callback_auth',
'as'=>'social.callback_auth'


]);


Route::group(['prefix' => 'user'], function () {

    Route::get('authorization', 'HomeController@authCheck')->name('user.authorization');

    Route::post('verification', 'HomeController@sendVcode')->name('user.send-vcode');
    Route::post('smsVerify', 'HomeController@smsVerify')->name('user.sms-verify');

    Route::post('verify-email', 'HomeController@sendEmailVcode')->name('user.send-emailVcode');
    Route::post('postEmailVerify', 'HomeController@postEmailVerify')->name('user.email-verify');


    Route::middleware(['CheckStatus'])->group(function () {
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/vogue/{trx}/{type}', 'PaymentController@purchaseVogue')->name('vogue');


        /*Manage escrow*/
        Route::get('/add-escrow', 'HomeController@addMilestone')->name('add.milestone');
        Route::post('/add-escrow', 'HomeController@storeEscrow')->name('storeEscrow');
        Route::get('/new-escrow', 'HomeController@createMilestone')->name('createMilestone');
        Route::post('/new-escrow', 'HomeController@storeMilestone')->name('storeMilestone');


        Route::get('/escrow-list', 'HomeController@milestoneByUser')->name('escrow.list');
        Route::get('/earning-list', 'HomeController@earningList')->name('earn.list');

        Route::get('trans/{code}','HomeController@viewMileStone')->name('get.mileStone.list');
        Route::get('earns/{code}','HomeController@viewEarnMileStone')->name('get.earnStone.list');
        Route::post('create-milestone','HomeController@getMileStone')->name('get.mileStone');
        Route::post('release-amount', 'HomeController@releaseAmount')->name('release.amount');
        Route::post('reject-amount', 'HomeController@rejectAmount')->name('reject.amount');

        Route::post('user-report', 'HomeController@userReport')->name('user.report');

        Route::post('messages', 'ChatsController@sendMessage')->name('store.message');
        Route::post('get-chat', 'ChatsController@getChat')->name('get.chat');


        Route::get('report-log/{code}', 'HomeController@reportLogAuthor')->name('report.log.author');

        Route::get('/deposit', ['uses' => 'HomeController@deposit', 'as' => 'deposit']);
        Route::post('/deposit', ['uses' => 'HomeController@deposit', 'as' => 'deposit']);
        Route::post('/deposit-data-insert', 'HomeController@depositDataInsert')->name('deposit.data-insert');
        Route::get('/deposit-preview', 'HomeController@depositPreview')->name('user.deposit.preview');
        Route::post('/deposit-confirm', 'PaymentController@depositConfirm')->name('deposit.confirm');

        Route::get('/withdraw-money', 'HomeController@withdrawMoney')->name('withdraw.money');
        Route::post('/withdraw-preview', 'HomeController@requestPreview')->name('withdraw.preview');
        Route::post('/withdraw-submit', 'HomeController@requestSubmit')->name('withdraw.submit');

        Route::get('/transaction-log', 'HomeController@activity')->name('user.trx');
        Route::get('/deposit-log', 'HomeController@depositLog')->name('user.depositLog');
        Route::get('/withdraw-log', 'HomeController@withdrawLog')->name('user.withdrawLog');

        Route::get('change-password', 'HomeController@changePassword')->name('user.change-password');
        Route::post('change-password', 'HomeController@submitPassword')->name('user.change-password');

        Route::get('edit-profile', 'HomeController@editProfile')->name('edit-profile');
        Route::post('edit-profile', 'HomeController@submitProfile')->name('edit-profile');
    });
});


Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'AdminLoginController@index')->name('admin.loginForm');
    Route::post('/', 'AdminLoginController@authenticate')->name('admin.login');
});


Route::group(['prefix' => 'admin', 'middleware' => 'auth:admin'], function () {


    /*demo start*/
    //Route::middleware(['demo'])->group(function () {

    Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');

    Route::get('reports', 'DashboardController@reports')->name('admin.reports');
    Route::get('reports/{id}', 'DashboardController@reportsAllView')->name('reports.view');
    Route::post('accept-milestone', 'DashboardController@milestoneAccepted')->name('milestone.accepted');
    Route::post('admin-report', 'DashboardController@storeReport')->name('admin.send.report');
    Route::post('get-chat', 'DashboardController@adminGetChat')->name('admin.get.chat');

    //    Blog Controller
    Route::get('/post-category', 'PostController@category')->name('admin.cat');
    Route::post('/post-category', 'PostController@UpdateCategory')->name('update.cat');
    Route::get('blog', 'PostController@index')->name('admin.blog');
    Route::get('blog/create', 'PostController@create')->name('blog.create');
    Route::post('blog/create', 'PostController@store')->name('blog.store');
    Route::delete('blog/delete', 'PostController@destroy')->name('blog.delete');
    Route::get('blog/edit/{id}', 'PostController@edit')->name('blog.edit');
    Route::post('blog-update', 'PostController@updatePost')->name('blog.update');

    //Our-client
    Route::get('our-client', 'OurClientController@ourClient')->name('our.client');
    Route::post('our-client', 'OurClientController@storeClient')->name('store.client');
    Route::delete('our-client', 'OurClientController@deleteClient')->name('delete.client');

    // Our-team
    Route::get('our-team', 'OurTeamController@ourTeam')->name('team');
    Route::get('our-team/create', 'OurTeamController@createOurTeam')->name('create.team');
    Route::post('our-team/create', 'OurTeamController@storeOurTeam')->name('store.team');
    Route::get('our-team/{id}', 'OurTeamController@editOurTeam')->name('edit.team');
    Route::post('our-team/{id}', 'OurTeamController@updateOurTeam')->name('update.team');
    Route::delete('our-team', 'OurTeamController@deleteOurTeam')->name('delete.team');

    //Slider

    Route::get('slider', 'WebSettingController@manageSlider')->name('slider');
    Route::post('slider', 'WebSettingController@storeSlider')->name('store.slider');
    Route::delete('slider', 'WebSettingController@deleteSlider')->name('slider-delete');


    //Gateway
    Route::get('/gateway', 'GatewayController@show')->name('gateway');
    Route::post('/gateway', 'GatewayController@update')->name('update.gateway');

    //Deposit
    Route::get('/deposits', 'DepositController@index')->name('deposits');
    Route::get('/deposits/requests', 'DepositController@requests')->name('deposits.requests');
    Route::put('/deposit/approve/{id}', 'DepositController@approve')->name('deposit.approve');
    Route::get('/deposit/{deposit}/delete', 'DepositController@destroy')->name('deposit.destroy');

    //withdraw

core/app/Report.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Report extends Model
{
    use SoftDeletes;
    protected $guarded = [];
    protected $table = "reports";


    public function reports()
    {
        return $this->belongsTo('App\Milestone', 'milestone_id', 'id');
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'report_from', 'id');
    }



    public function receiver()
    {
        return $this->belongsTo('App\User', 'report_against', 'id');
    }

    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->diffForHumans();
    }
}

core/resources/views/admin/pages/reports-list.blade.php
@extends('admin.layout.master')
@section('css')
    <link href="{{ asset('assets/front/css/report-chat.css') }}" rel="stylesheet">
@stop
@section('body')

    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="mailbox-controls">
                    <div class="tile-title ">
                        <h4 class="name">Conversation for: {{$milestone->title}}
                            ({{$milestone->amount}} {{$basic->currency}} )</h4>
                    </div>
                    <p>
                        @php $user_id = []; @endphp
                        @foreach($reports as $data)
                            @if(!in_array($data->report_from, $user_id))
                                @if($data->report_from !=0)
                                    <button class="btn btn-primary icon-btn milestone_button"
                                            data-milestone="{{$milestone_id}}"
                                            data-user="{{$data->user->id}}"
                                            data-username="{{$data->user->name}}"
                                            data-toggle="modal" data-target="#payButton">
                                        <i class="fa fa-user"></i>
                                        {{$data->user->name}}</button>
                                    @php $user_id[] = $data->report_from; @endphp
                                @endif
                            @endif
                        @endforeach


                    </p>
                </div>
                <div class="tile-body">


                    <div class="panel panel-primary panel-custom " id="app"><!-- single pricing table -->
                        <div class="panel-body" id="messages">
                            <ul class="chat" id="message_append_body">


                                @foreach($reports as $data)
                                    <li class="@if( $data->report_from == 0) right  @else left @endif  clearfix chat-length messages"
                                        data-length="{{ $data->id }}">
                                    <span class="chat-img @if( $data->report_from != 0) pull-left @else pull-right @endif ">
                                        @if($data->report_from!=0)
                                            @php $string = $data->user->username @endphp
                                            <img src="http://placehold.it/50/55C1E7/fff&text={{strtoupper($string[0])}}"
                                                 alt="User Avatar"
                                                 class="img-circle border-radius-50"/>
                                        @else
                                            <img src="http://placehold.it/50/FA6F57/fff&text=A"
                                                 alt="User Avatar"
                                                 class="img-circle border-radius-50"/>

                                        @endif


                                    </span>
                                        <div class="chat-body clearfix">
                                            <div class="header">

                                                @if($data->report_from!=0)
                                                    <strong class="primary-font">{{$data->user->username}}</strong>
                                                    <small class="pull-right text-muted">
                                                        <span class="glyphicon glyphicon-time"></span>{{$data->created_at}}
                                                    </small>
                                                @else

                                                    <small class="text-muted">
                                                        <span class="glyphicon glyphicon-time"></span>{{$data->created_at}}
                                                    </small>
                                                    <strong class="pull-right primary-font">Admin</strong>
                                                @endif


                                            </div>
                                            <p>{!! $data->report !!}</p>
                                        </div>
                                    </li>
                                @endforeach
                            </ul>


                            <!-- //.content form wrapper -->
                        </div>
                        <div class="panel-footer">
                            <form id="sendMessage" onsubmit="sendMessage(event)">
                                @csrf
                                <div class="input-group">
                                    <input type="hidden" name="report_against" id="report_against" value="0">
                                    <input type="hidden" name="milestone_id" id="milestone_id"
                                           value="{{$milestone_id}}">
                                    <input type="hidden" name="amount" id="amount" value="{{$amount}}">

                                    <input id="btn-input" type="text" name="report" class="form-control input-lg"
                                           placeholder="Type your message here..." autocomplete="off"/>
                                    <span class="input-group-btn">
                                        <button type="button" class="btn btn-primary custom-sbtn btn-lg" id="btn-chat">
                                            Send
                                        </button>
                                    </span>
                                </div>
                                <p class="eml"></p>
                            </form>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>



    <div class="modal fade editModal" id="payButton" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel2"><strong>Confirm Milestone Request</strong></h4>

                    <button type="button" class="btn btn-default btn-xs pull-right"
                            data-dismiss="modal">X
                    </button>
                </div>


                <form method="post" action="{{route('milestone.accepted')}}">
                    @csrf
                    <div class="modal-body">
                        <p>Are you sure to added balance to '<strong id="username"></strong>' ??</p>
                        <input type="hidden" name="milestone_id" id="get_milestone_id">
                        <input type="hidden" name="user_id" id="user_id">
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Yes</button>
                        <button class="btn btn-danger" data-dismiss="modal" aria-label="Close"><i
                                    class="fa fa-times"></i> No
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>


@endsection

@section('script')
    <script type="text/javascript">

        $(document).on('click', '.milestone_button', function () {
            var milestoneId = $(this).data('milestone');
            var userId = $(this).data('user');
            var username = $(this).data('username');
            $('#get_milestone_id').val(milestoneId);
            $('#user_id').val(userId);
            $('#username').text(username);
        });


        $(document).ready(function () {
            setInterval(function () {
                var length = $('.chat').find('.chat-length:last').data('length');
                if (typeof length === "undefined") {
                    length = 0;
                }
                var user = "0";
                var user2 = "{{ Auth::guard('web')->user()->id}} ";
                var report_against = $('#report_against').val();
                var milestone_id = $('#milestone_id').val();
                var amount = $('#amount').val();
                $.ajax({
                    url: '{{ route('admin.get.chat') }}',
                    type: 'post',
                    data: {
                        length: length,
                        report_from: user,
                        report_against: report_against,
                        milestone_id: milestone_id,
                        amount: amount
                    },
                    success: function (data) {
                        $.each(data, function (key, val) {
                            var auth = "admin";

                            var newSender = (val.user != null) ? val.user.username : 'a';
                            var name = (val.report_from == user) ? auth.substr(0, 1) : newSender.substr(0, 1);
                            var name2 = (val.report_from == user2) ? auth.substr(0, 1) : newSender.substr(0, 1);
                            if (user == val.report_from) {
                                var html = '<li class="right clearfix chat-length" data-length="' + val.id + '"><span class="chat-img pull-right">\n' +
                                    '                            <img src="http://placehold.it/50/FA6F57/fff&text=A" alt="User Avatar" class="img-circle border-radius-50" />\n' +
                                    '                        </span>\n' +
                                    '                            <div class="chat-body clearfix">\n' +
                                    '                                <div class="header">\n' +
                                    '                                    <small class=" text-muted"><span class=" glyphicon glyphicon-time"></span>' + val.created_at + '</small>' +
                                    '                                   <strong class="pull-right  primary-font">Admin</strong>' +
                                    '                               </div>\n' +
                                    '                                <p>\n' + val.report +
                                    '                                </p>\n' +
                                    '                            </div>\n' +
                                    '                        </li>'
                            } else {

                                var html = '<li class="left clearfix chat-length" data-length="' + val.id + '"><span class="chat-img pull-left">\n' +
                                    '                            <img src="http://placehold.it/50/55C1E7/fff&text=' + name.toUpperCase() + '" alt="User Avatar" class="img-circle border-radius-50" />\n' +
                                    '                        </span>\n' +
                                    '                            <div class="chat-body clearfix">\n' +
                                    '                                <div class="header">\n' +
                                    '                                    <strong class="primary-font">' + newSender + '</strong>' +
                                    '                                       <small class="pull-right text-muted"><span class="glyphicon glyphicon-time"></span>' + val.created_at + '</small>\n' +
                                    '                                </div>\n' +
                                    '                                <p>\n' + val.report +
                                    '                                </p>\n' +
                                    '                            </div>\n' +
                                    '                        </li>'
                            }
                            $('#message_append_body').append(html).ready(function () {
                                var elem = document.getElementById('messages');
                                elem.scrollTop = elem.scrollHeight;
                            });

                        });
                    }
                });
            }, 2000)
        });


        function sendMessage(e) {
            e.preventDefault();
            var form = document.getElementById('sendMessage');
            var fd = new FormData(form);
            $.ajax({
                url: '{{route('admin.send.report')}}',
                type: 'POST',
                data: fd,
                contentType: false,
                processData: false,
                success: function (data) {
                    $('.input-lg').val('');
                }
            });
        }

        $(document).ready(function () {
            var elem = document.getElementById('messages');
            elem.scrollTop = elem.scrollHeight;
        })

    </script>
@stop

core/resources/views/admin/pages/reports.blade.php
@extends('admin.layout.master')

@section('body')
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="tile-title ">
                </div>
                <div class="tile-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" >
                            <thead>
                            <tr>
                                <th>SL</th>
                                <th> Report From </th>
                                <th>Milestone Title</th>
                                <th>Message</th>
                                <th>ACTION</th>
                            </tr>
                            </thead>

                            <tbody>
                            @foreach($reports as $k=>$dep)
                                @php
                                    $data = App\Report::where('milestone_id',$dep->milestone_id)->latest()->where('report_from','!=',0)->first();
                                @endphp

                                    <tr>
                                        <td>{{++$k}}</td>
                                        <td>
                                            @if($data->report_from != 0)
                                            <a href="{{route('user.single', $data->user->id)}}">
                                                {{$data->user->username or ''}}
                                            </a>
                                                @else
                                                <a >
                                                    Admin
                                                </a>
                                            @endif
                                        </td>
                                        <td>
                                                {{  $data->reports->title}}
                                        </td>

                                        <td>
                                            @if($data->is_read == 0)
                                                <b>{{  $data->report}}</b>
                                            @else
                                                {{  $data->report}}
                                            @endif
                                        </td>
                                        <td>
                                            <a href="{{route('reports.view',$data->milestone_id)}}" class="btn btn-outline-primary btn-sm" >
                                                <i class="fa fa-eye"></i> view </a>
                                        </td>
                                    </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>

                    {{$reports->links()}}
                </div>

            </div>
        </div>
    </div>



@endsection

@section('script')
@stop

core/resources/views/admin/pages/subscriber-email.blade.php
@extends('admin.layout.master')

@section('body')
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="tile-title ">
                    <a href="{{route('manage.subscribers')}}" class="btn btn-success btn-md pull-right ">
                        <i class="fa fa-eye"></i> View Subscribers
                    </a>

                    <br>
                </div>
                <div class="tile-body">
                    <form role="form" method="POST" action="{{route('send.email.subscriber')}}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="form-body">
                            <div class="form-group">
                                <label><strong>Subject</strong></label>
                                <input type="text" name="subject" class="form-control input-lg" value="">
                            </div>
                            <div class="form-group">
                                <label><strong>Email Message</strong></label>
                                <textarea class="form-control" name="emailMessage" rows="10">

                                                </textarea>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="submit-btn btn btn-primary btn-lg btn-block login-button">Send Email</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection